### PR TITLE
removed string limitation to seperator lines

### PR DESCRIPTION
**Pull request by aemarco**
again some improvement on seperator lines.
before only ConsoleMenu<string>, now ConsoleMenu<T>

### CODE REVIEW

**Review by arthurvaverko-kaltura — CHANGES_REQUESTED** [review]
What about backward compatibility ?
Its a good design to make the consul item abstract but i would like to preserve backward computability.

I suggest making a BaseConsuleMenuItem abstract and make the existing ConsulMenuItem<T> derive and implement the abstract method with T .

What do you think ?

**Comment by aemarco** [comment]
The only point may cause problems is
public ConsoleMenuItem[] _MenuItems { get; set; }
In my opinion that should be private anyways since its fed through the constructor.

If that is used externally somewhere, than it may cause **minor** problems :(
Just considered some workarounds here, but since there is also a setter, it would create other probs.

In my opinion, the seperators an all types is worth the hassle.

**Comment by arthurvaverko-kaltura** [comment]
The property hiding braking change i can live with. Just don wabt all users who already use generics to start creating their own classes just to upgrade.

**Comment by aemarco** [comment]
made the change ;)

**Pull request merged**
