### PR TITLE
Converted to .Net Standard 2.0

### PR DESCRIPTION
**Pull request by mennan**
This project converted from .Net Framework 4.5.2 to .Net Standard 2.0.

### CODE REVIEW

**Comment by arthurvaverko-kaltura** [comment]
thanks for the pull, but i can merge it as there is a CI process that fails, it cannot be converted it needs to supot multiple targets, see here: https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks

**Comment by mennan** [comment]
Hi @arthurvaverko,

I added .Net Framework 4.7 to target frameworks. But CI has failed. What is AppVeyor MSBuild version?

Maybe this link can help.
https://help.appveyor.com/discussions/problems/10350-appveyoyr-fails-to-build-aspnet-core-webapi-project

**Comment by mennan** [comment]
@arthurvaverko When will it be merged?

**Comment by arthurvaverko-kaltura** [comment]
Ill do my best to check the build on the next cuple of days ... Thanks .. and ill merge

**Comment by arthurvaverko-kaltura** [comment]
this is what i get in AppVeyor

```
uild started
git clone -q https://github.com/arthurvaverko/ConsoleMenu.git C:\projects\consolemenu
git fetch -q origin +refs/pull/2/merge:
git checkout -qf FETCH_HEAD
Patching AssemblyInfo
No AssemblyInfo files found matching '**\AssemblyInfo.*'
msbuild "C:\projects\consolemenu\ConsoleMenu.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.
C:\projects\consolemenu\ConsoleMenu\ConsoleMenu.csproj(1,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
C:\projects\consolemenu\ConsoleMenuTest\ConsoleMenuTest.csproj(1,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
Command exited with code 1
```

**Pull request merged**
